version: "3"
services:
  lucky:
    image: python:3.9
    volumes:
      - ./freeAI:/app
    working_dir: /app
    command: python lucky/lucky.py
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
